### ISSUE TITLE
TypeError: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by piotrekfracek** [vhf/bplustree#1]
Hi,
I found that there is something wrong in your code. 

I got this error.

```
TypeError: Cannot read property '0' of undefined
    at BPlusTree.fetchRange (/Users/dex/cloud/dev/praca-magisterska/node_modules/bplustree/dist/bplustree.js:146:20)
```

It seems that `leaf.k` sometimes is `false`.

**Comment by vhf** [comment]
Hi, 
Thanks, I'll look into it. Could you please provide code reproducing the bug?

**Comment by piotrekfracek** [comment]
Sadly it's quite complicated code. I have 1000000 geo points stored with integer geohash as a key. Then every 5 ms I perform search operation (fetchRange).

Worryingly error happens only sometimes (~every 1000 operations)

**Comment by piotrekfracek** [comment]
@vhf 

It may be related with fetch method.

Here (https://github.com/vhf/bplustree/blob/master/lib/bplustree.js#L102) you're trying to iterate while index is lower than value stored in leaf.

Few lines later (https://github.com/vhf/bplustree/blob/master/lib/bplustree.js#L116) next leaf is fetching.

Probably there is no next leaf and method returns `false` (https://github.com/vhf/bplustree/blob/master/lib/bplustree.js#L264)

In next while loop iteration `leaf` is `false` (`leaf.k` is `undefined`) so `while (leaf.k[index] <= hi)` here we have an error.

And it seems to be true, because it happens when `upperBound` is really close to highest key stored in tree (it may be in last leaf)
I.e.

```
upperBound = 3700306512012590
higestKey  = 3700306512112589
```

**Comment by vhf** [comment]
Thanks for your investigation.

I'll try to debug this. In the meantime, it might be interesting to pass the `debug` option when creating the tree, to check if it ends up being invalid or not.

**Comment by vhf** [comment]
It's also worth keeping in mind that JavaScript's max safe number is `9007199254740991`, which is really close to your `upperBound`.

**Comment by vhf** [comment]
@piotrekfracek I'd be very interested to know how you build the tree.

Do you only store things, or do you store things and also delete things? Could you give a rough overview of you work with it? Might help reproducing this.
