### ISSUE TITLE
Remove babel-polyfill as a dependency?

### ISSUE THREAD

**Issue by stevendesu** [vhf/bplustree#3]
I was looking for an efficient B Tree (or B+ Tree) implementation for [my own library](https://www.npmjs.com/package/jsindex) I recently started working on and I stumbled upon this. I was hoping to try it out, but the first thing I did was take a peek at the dependencies to ensure I wasn't bringing in 40,000 lines of code for a data structure I could implement in a few hundred.

The only two dependencies listed were `babel-polyfill` and `regenerator-runtime`

According to [Babel's documentation on `babel-polyfill`](https://babeljs.io/docs/en/babel-polyfill), it should only be included in *applications*, not *libraries*. Because it's a polyfill for an environment, it's possible someone may write an application that doesn't need it (for example, if they're writing a Node CLI application that doesn't have to run in Internet Explorer)

I haven't looked into the source yet for your library to figure out where or why you're including this, but I assume it can be left out without imposing a huge cost on developers -- especially now that most browsers support ES2015+ by default

I suspect that `regenerator-runtime` is similar. Because it's a runtime, it likely should be included with applications and not with libraries. A quick glance at [their GitHub](https://github.com/facebook/regenerator), however, suggests that they provide a `wrapGenerator` function -- so I think it's more tightly coupled and cannot just be left out like `babel-polyfill` can

Also worth noting, it looks like `regenerator-runtime` is already included in `babel-polyfill`:

```
~/src/jsindex$ npm list --only=prod
jsindex@0.2.0 /home/sbarnett/src/jsindex
├─┬ bplustree@1.2.2
│ ├─┬ babel-polyfill@6.26.0
│ │ ├─┬ babel-runtime@6.26.0
│ │ │ ├── core-js@2.5.7 deduped
│ │ │ └── regenerator-runtime@0.11.1
│ │ ├── core-js@2.5.7
│ │ └── regenerator-runtime@0.10.5
│ └── regenerator-runtime@0.9.6
├── csv-parse@3.2.0
└─┬ csv-stringify@4.3.1
  └── lodash.get@4.4.2
```

**Comment by vhf** [comment]
@stevendesu I'm sure we can get rid of it, it was needed when I wrote this lib because ES2015 support was obviously very poor in 2015!

I'll give it a try.

**Comment by vhf** [comment]
@stevendesu Take a look at @2.0.0.

**Comment by stevendesu** [comment]
@vhf 
```
~/src/jsindex$ npm list --only=prod
jsindex@0.2.0 /home/sbarnett/src/jsindex
├── bplustree@2.0.0
├── csv-parse@3.2.0
└─┬ csv-stringify@4.3.1
  └── lodash.get@4.4.2
```

So far it looks good :smile: I'll run a few local tests and see if it works as expected

**Comment by stevendesu** [comment]
The library seems to function, but I discovered an unrelated bug. I'm going to see if the unrelated bug repros in `v1.2.2`. If it does, I'll open a separate bug report. If not, I'll assume it's related to removing one of these two dependencies.

**Comment by stevendesu** [comment]
My issue repro'd in `v1.2.2`, so this is good to leave closed and I'll open a new ticket
